name: library_app_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.3
  gap: ^3.0.1
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  dartz: ^0.10.1
  image_picker: ^1.1.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
